[build]
  publish = "dist"
  command = "npm run build"

[context.production.environment]
  VITE_WHATSAPP_NUMBER = "31983584949"
  VITE_WHATSAPP_MESSAGE = "Olá, tenho uma dúvida."

[context.deploy-preview.environment]
  VITE_WHATSAPP_NUMBER = "31983584949"
  VITE_WHATSAPP_MESSAGE = "Olá, tenho uma dúvida."

[context.branch-deploy.environment]
  VITE_WHATSAPP_NUMBER = "31983584949"
  VITE_WHATSAPP_MESSAGE = "Olá, tenho uma dúvida."

# Configurações de redirecionamento para SPA
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
